name: Pipeline
on: 
  push:
    branches:
      - main

jobs:    
  lint:    
    name: 'Linting'
    runs-on: ubuntu-latest
    steps:  
      - name: 'Install flake8'
        run: pip install flake8

      - name: 'Install pylint'
        run: pip install pylint          
      
      - name: 'Checkout repo de matichewer/eati2023-pipeline@main'
        uses: actions/checkout@v3
        with:
          repository: matichewer/eati2023-pipeline
          ref: main
          path: .

      - name: 'Execute tree'
        run: tree

      - name: 'Execute flake8'
        run: flake8 main.py

      - name: 'Execute pylint'
        run: pylint main.py

  unit_test:
    name: 'Unit test'  
    runs-on: ubuntu-latest
    needs: [lint]
    steps:        
      - name: 'Checkout repo de matichewer/eati2023-pipeline@main'
        uses: actions/checkout@v3
        with:
          repository: matichewer/eati2023-pipeline
          ref: main
          path: .

      - name: 'Ejecuto el Unit Test'
        run: python -m unittest --verbose --failfast

  build:
    name: 'Build'  
    runs-on: ubuntu-latest
    needs: [unit_test]
    steps: 
      - name: 'Checkout repo de matichewer/eati2023-pipeline@main'
        uses: actions/checkout@v3
        with:
          repository: matichewer/eati2023-pipeline
          ref: main
          path: .

      - name: 'Ejecuto main.py'
        run: python main.py
    
      - name: 'Subo lo generado por main.py a un artefacto'
        uses: actions/upload-artifact@v3
        with:
          name: Mi-artefacto
          path: build/
       
  deploy:
    name: 'Deploy'  
    runs-on: ubuntu-latest
    needs: [build]
    steps:          
      - name: 'Descargo artefacto generado por main.py'
        uses: actions/download-artifact@v3
        with:
          name: Mi-artefacto
          path: ./build

      - name: 'Envio index.html al servidor haciendo un POST'
        run: |
          http_code=$(curl -v --stderr deploy.log -w "%{http_code}\n" -F password=${{ secrets.PASSWORD }} -F file=@build/index.html -F user=${{ secrets.USER }} https://cs.uns.edu.ar/~jose.moyano/index.php)
          echo 'http code: ${http_code}'
          if [ ${http_code} -eq '200' ]; then
            echo 'Exito'
          else
              echo 'Error'
          fi

      - name: 'Execute tree'
        run: tree

      - name: 'Subiendo el log del deploy'
        uses: actions/upload-artifact@v3 
        with:
          name: deploy
          path: deploy.log