name: Pipeline
on: 
  push:
    branches:
      - main

env:
  FILE_PATH: 'build/index.html'

jobs:    
  lint:    
    name: 'Linting Job'
    runs-on: ubuntu-latest
    steps:  
      - name: 'Install flake8'
        run: pip install flake8

      - name: 'Install pylint'
        run: pip install pylint  
   
      - name: 'Execute flake8'
        run: flake8 main.py

      - name: 'Execute pylint'
        run: pylint main.py

  unit_test:
    name: 'Unit Test Job'  
    runs-on: ubuntu-latest
    needs: [lint]
    steps:  
      - run: python -m unittest --verbose --failfast

  build:
    name: 'Build Job'  
    runs-on: ubuntu-latest
    needs: [unit_test]
    steps:  
      - name: 'Ejecuto main.py'
        run: python main.py
    
      - name: 'Subo lo generado por main.py a un artefacto'
        uses: actions/upload-artifact@v3
        with:
          name: Mi-artefacto
          path: ${{ env.FILE_PATH }}
       
  deploy:
    name: 'Deploy Job'  
    runs-on: ubuntu-latest
    needs: [build]
    steps:          
      - name: 'Descargo artefacto generado por main.py'
        uses: actions/download-artifact@v3
        with:
          name: Mi-artefacto
          path: ${{ env.PATH_FILE }}
       
    

        
